<?php

namespace Database\Seeders;

use App\Models\Approver;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ApproverSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            [
                'approver_type' => 'Approver1',
                'name' => 'Apple Hurtado',
                'email' => 'rphurtado@joy-nostalg.com',
                'unit' => 'PROPERTY DEVELOPMENT UNIT',
                'type' => 'MIDDLE CONDO',
                'department' => 'PD & Marketing',
                'cost_center' => 'PDU-MC-PDT-PDM',
                'budget_line_charging_1' => 'MSE',
                'gl_account' => '533401',
                'budget_line_charging_2' => 'SOE-SA-Vehicle Support',
                'product' => 'SOE-SA-VEHICLE SUPPORT',
            ],
            [
                'approver_type' => 'Approver2',
                'name' => 'Jett Mendoza',
                'email' => 'ksmendoza@joy-nostalg.com',
                'unit' => 'PROPERTY DEVELOPMENT UNIT',
                'type' => 'MIDDLE CONDO',
                'department' => 'PD & Marketing',
                'cost_center' => 'PDU-MC-PDT-PDM',
                'budget_line_charging_1' => 'MSE',
                'gl_account' => '533401',
                'budget_line_charging_2' => 'SOE-SA-Vehicle Support',
                'product' => 'SOE-SA-VEHICLE SUPPORT',
            ],
            [
                'approver_type' => 'Approver1',
                'name' => 'Jett Mendoza',
                'email' => 'ksmendoza@joy-nostalg.com',
                'unit' => 'PROPERTY DEVELOPMENT UNIT',
                'type' => 'MIDDLE CONDO',
                'department' => 'Sales Management',
                'cost_center' => 'PDU-MC-PDT-SMD',
                'budget_line_charging_1' => 'MSE',
                'gl_account' => '533401',
                'budget_line_charging_2' => 'SOE-SA-Vehicle Support',
                'product' => 'SOE-SA-VEHICLE SUPPORT',
            ],
            [
                'approver_type' => 'Approver1',
                'name' => 'Jett Mendoza',
                'email' => 'ksmendoza@joy-nostalg.com',
                'unit' => 'PROPERTY DEVELOPMENT UNIT',
                'type' => 'MIDDLE CONDO',
                'department' => 'Customer Advocacy',
                'cost_center' => 'PDU-MC-PDT-CAD',
                'budget_line_charging_1' => 'MSE',
                'gl_account' => '533401',
                'budget_line_charging_2' => 'SOE-SA-Vehicle Support',
                'product' => 'SOE-SA-VEHICLE SUPPORT',
            ],


            [
                'approver_type' => 'Approver1',
                'name' => 'Apple Hurtado',
                'email' => 'rphurtado@joy-nostalg.com',
                'unit' => 'PROPERTY DEVELOPMENT UNIT',
                'type' => 'MIDDLE HOUSING',
                'department' => 'PD & Marketing',
                'cost_center' => 'PDU-MC-PDT-PDM',
                'budget_line_charging_1' => 'MSE',
                'gl_account' => '533401',
                'budget_line_charging_2' => 'SOE-SA-Vehicle Support',
                'product' => 'SOE-SA-VEHICLE SUPPORT',
            ],
            [
                'approver_type' => 'Approver2',
                'name' => 'Jett Mendoza',
                'email' => 'ksmendoza@joy-nostalg.com',
                'unit' => 'PROPERTY DEVELOPMENT UNIT',
                'type' => 'MIDDLE HOUSING',
                'department' => 'PD & Marketing',
                'cost_center' => 'PDU-MC-PDT-PDM',
                'budget_line_charging_1' => 'MSE',
                'gl_account' => '533401',
                'budget_line_charging_2' => 'SOE-SA-Vehicle Support',
                'product' => 'SOE-SA-VEHICLE SUPPORT',
            ],
            [
                'approver_type' => 'Approver1',
                'name' => 'Jett Mendoza',
                'email' => 'ksmendoza@joy-nostalg.com',
                'unit' => 'PROPERTY DEVELOPMENT UNIT',
                'type' => 'MIDDLE HOUSING',
                'department' => 'Sales Management',
                'cost_center' => 'PDU-MC-PDT-SMD',
                'budget_line_charging_1' => 'MSE',
                'gl_account' => '533401',
                'budget_line_charging_2' => 'SOE-SA-Vehicle Support',
                'product' => 'SOE-SA-VEHICLE SUPPORT',
            ],
            [
                'approver_type' => 'Approver1',
                'name' => 'Jett Mendoza',
                'email' => 'ksmendoza@joy-nostalg.com',
                'unit' => 'PROPERTY DEVELOPMENT UNIT',
                'type' => 'MIDDLE HOUSING',
                'department' => 'Customer Advocacy',
                'cost_center' => 'PDU-MC-PDT-CAD',
                'budget_line_charging_1' => 'MSE',
                'gl_account' => '533401',
                'budget_line_charging_2' => 'SOE-SA-Vehicle Support',
                'product' => 'SOE-SA-VEHICLE SUPPORT',
            ],
            
            [
                'approver_type' => 'Approver1',
                'name' => 'Michael Ngo',
                'email' => 'msngo.everyhome@joy-nostalg.com',
                'unit' => 'PROPERTY DEVELOPMENT UNIT',
                'type' => 'ECONOMIC MID',
                'department' => 'PD & Marketing',
                'cost_center' => 'PDU-EHG-PDT-PDM',
                'budget_line_charging_1' => 'MSE',
                'gl_account' => '533401',
                'budget_line_charging_2' => 'SOE-SA-Vehicle Support',
                'product' => 'SOE-SA-VEHICLE SUPPORT',
            ],
            [
                'approver_type' => 'Approver1',
                'name' => 'Susan Alcabao',
                'email' => 'spalcabao.everyhome@joy-nostalg.com',
                'unit' => 'PROPERTY DEVELOPMENT UNIT',
                'type' => 'ECONOMIC MID',
                'department' => 'Sales Management',
                'cost_center' => 'PDU-EHG-PDT-SMD',
                'budget_line_charging_1' => 'MSE',
                'gl_account' => '533401',
                'budget_line_charging_2' => 'SOE-SA-Vehicle Support',
                'product' => 'SOE-SA-VEHICLE SUPPORT',
            ],
            [
                'approver_type' => 'Approver2',
                'name' => 'Michael Ngo',
                'email' => 'msngo.everyhome@joy-nostalg.com',
                'unit' => 'PROPERTY DEVELOPMENT UNIT',
                'type' => 'ECONOMIC MID',
                'department' => 'Sales Management',
                'cost_center' => 'PDU-EHG-PDT-SMD',
                'budget_line_charging_1' => 'MSE',
                'gl_account' => '533401',
                'budget_line_charging_2' => 'SOE-SA-Vehicle Support',
                'product' => 'SOE-SA-VEHICLE SUPPORT',
            ],
            [
                'approver_type' => 'Approver1',
                'name' => 'Amor Calcabin',
                'email' => 'abcalcabin.extraordinary@joy-nostalg.com',
                'unit' => 'PROPERTY DEVELOPMENT UNIT',
                'type' => 'ECONOMIC MID',
                'department' => 'Fulfillment Operations',
                'cost_center' => 'PDU-EHG-PDT-FOD',
                'budget_line_charging_1' => 'MSE',
                'gl_account' => '533401',
                'budget_line_charging_2' => 'SOE-SA-Vehicle Support',
                'product' => 'SOE-SA-VEHICLE SUPPORT',
            ],
            [
                'approver_type' => 'Approver2',
                'name' => 'Michael Ngo',
                'email' => 'msngo.everyhome@joy-nostalg.com',
                'unit' => 'PROPERTY DEVELOPMENT UNIT',
                'type' => 'ECONOMIC MID',
                'department' => 'Fulfillment Operations',
                'cost_center' => 'PDU-EHG-PDT-FOD',
                'budget_line_charging_1' => 'MSE',
                'gl_account' => '533401',
                'budget_line_charging_2' => 'SOE-SA-Vehicle Support',
                'product' => 'SOE-SA-VEHICLE SUPPORT',
            ],
            
            [
                'approver_type' => 'Approver1',
                'name' => 'Adrian Cantor',
                'email' => 'accantor.extraordinary@joy-nostalg.com',
                'unit' => 'PROPERTY DEVELOPMENT UNIT',
                'type' => 'ECONOMIC LOW',
                'department' => 'PD & Marketing',
                'cost_center' => 'PDU-SHG-ELG-PDT-PDM',
                'budget_line_charging_1' => 'MSE',
                'gl_account' => '533401',
                'budget_line_charging_2' => 'SOE-SA-Vehicle Support',
                'product' => 'SOE-SA-VEHICLE SUPPORT',
            ],
            [
                'approver_type' => 'Approver2',
                'name' => 'Ranulfo Ortiz',
                'email' => 'ruortiz@joy-nostalg.com',
                'unit' => 'PROPERTY DEVELOPMENT UNIT',
                'type' => 'ECONOMIC LOW',
                'department' => 'PD & Marketing',
                'cost_center' => 'PDU-SHG-ELG-PDT-PDM',
                'budget_line_charging_1' => 'MSE',
                'gl_account' => '533401',
                'budget_line_charging_2' => 'SOE-SA-Vehicle Support',
                'product' => 'SOE-SA-VEHICLE SUPPORT',
            ],
            [
                'approver_type' => 'Approver2',
                'name' => 'Joey Ng',
                'email' => 'joey.ng@joy-nostalg.com',
                'unit' => 'PROPERTY DEVELOPMENT UNIT',
                'type' => 'ECONOMIC LOW',
                'department' => 'PD & Marketing',
                'cost_center' => 'PDU-SHG-ELG-PDT-PDM',
                'budget_line_charging_1' => 'MSE',
                'gl_account' => '533401',
                'budget_line_charging_2' => 'SOE-SA-Vehicle Support',
                'product' => 'SOE-SA-VEHICLE SUPPORT',
            ],
            [
                'approver_type' => 'Approver1',
                'name' => 'Johnny Iconar III',
                'email' => 'jdiconar.extraordinary@joy-nostalg.com',
                'unit' => 'PROPERTY DEVELOPMENT UNIT',
                'type' => 'ECONOMIC LOW',
                'department' => 'Sales Management',
                'cost_center' => 'PDU-SHG-ELG-PDT-SMD',
                'budget_line_charging_1' => 'MSE',
                'gl_account' => '533401',
                'budget_line_charging_2' => 'SOE-SA-Vehicle Support',
                'product' => 'SOE-SA-VEHICLE SUPPORT',
            ],
            [
                'approver_type' => 'Approver2',
                'name' => 'Ranulfo Ortiz',
                'email' => 'ruortiz@joy-nostalg.com',
                'unit' => 'PROPERTY DEVELOPMENT UNIT',
                'type' => 'ECONOMIC LOW',
                'department' => 'Sales Management',
                'cost_center' => 'PDU-SHG-ELG-PDT-SMD',
                'budget_line_charging_1' => 'MSE',
                'gl_account' => '533401',
                'budget_line_charging_2' => 'SOE-SA-Vehicle Support',
                'product' => 'SOE-SA-VEHICLE SUPPORT',
            ],
            [
                'approver_type' => 'Approver2',
                'name' => 'Joey Ng',
                'email' => 'joey.ng@joy-nostalg.com',
                'unit' => 'PROPERTY DEVELOPMENT UNIT',
                'type' => 'ECONOMIC LOW',
                'department' => 'Sales Management',
                'cost_center' => 'PDU-SHG-ELG-PDT-SMD',
                'budget_line_charging_1' => 'MSE',
                'gl_account' => '533401',
                'budget_line_charging_2' => 'SOE-SA-Vehicle Support',
                'product' => 'SOE-SA-VEHICLE SUPPORT',
            ],
            [
                'approver_type' => 'Approver1',
                'name' => 'Amor Calcabin',
                'email' => 'abcalcabin.extraordinary@joy-nostalg.com',
                'unit' => 'PROPERTY DEVELOPMENT UNIT',
                'type' => 'ECONOMIC LOW',
                'department' => 'Fulfillment Operations',
                'cost_center' => 'PDU-SHG-ELG-PDT-FOD',
                'budget_line_charging_1' => 'MSE',
                'gl_account' => '533401',
                'budget_line_charging_2' => 'SOE-SA-Vehicle Support',
                'product' => 'SOE-SA-VEHICLE SUPPORT',
            ],
            [
                'approver_type' => 'Approver2',
                'name' => 'Ranulfo Ortiz',
                'email' => 'ruortiz@joy-nostalg.com',
                'unit' => 'PROPERTY DEVELOPMENT UNIT',
                'type' => 'ECONOMIC LOW',
                'department' => 'Fulfillment Operations',
                'cost_center' => 'PDU-SHG-ELG-PDT-FOD',
                'budget_line_charging_1' => 'MSE',
                'gl_account' => '533401',
                'budget_line_charging_2' => 'SOE-SA-Vehicle Support',
                'product' => 'SOE-SA-VEHICLE SUPPORT',
            ],
            [
                'approver_type' => 'Approver2',
                'name' => 'Joey Ng',
                'email' => 'joey.ng@joy-nostalg.com',
                'unit' => 'PROPERTY DEVELOPMENT UNIT',
                'type' => 'ECONOMIC LOW',
                'department' => 'Fulfillment Operations',
                'cost_center' => 'PDU-SHG-ELG-PDT-FOD',
                'budget_line_charging_1' => 'MSE',
                'gl_account' => '533401',
                'budget_line_charging_2' => 'SOE-SA-Vehicle Support',
                'product' => 'SOE-SA-VEHICLE SUPPORT',
            ],
            
            [
                'approver_type' => 'Approver1',
                'name' => 'Adrian Cantor',
                'email' => 'accantor.extraordinary@joy-nostalg.com',
                'unit' => 'PROPERTY DEVELOPMENT UNIT',
                'type' => 'SOCIALIZED',
                'department' => 'PD & Marketing',
                'cost_center' => 'PDU-SHG-PDT-PDM',
                'budget_line_charging_1' => 'MSE',
                'gl_account' => '533401',
                'budget_line_charging_2' => 'SOE-SA-Vehicle Support',
                'product' => 'SOE-SA-VEHICLE SUPPORT',
            ],
            [
                'approver_type' => 'Approver2',
                'name' => 'Ranulfo Ortiz',
                'email' => 'ruortiz@joy-nostalg.com',
                'unit' => 'PROPERTY DEVELOPMENT UNIT',
                'type' => 'SOCIALIZED',
                'department' => 'PD & Marketing',
                'cost_center' => 'PDU-SHG-PDT-PDM',
                'budget_line_charging_1' => 'MSE',
                'gl_account' => '533401',
                'budget_line_charging_2' => 'SOE-SA-Vehicle Support',
                'product' => 'SOE-SA-VEHICLE SUPPORT',
            ],
            [
                'approver_type' => 'Approver2',
                'name' => 'Joey Ng',
                'email' => 'joey.ng@joy-nostalg.com',
                'unit' => 'PROPERTY DEVELOPMENT UNIT',
                'type' => 'SOCIALIZED',
                'department' => 'PD & Marketing',
                'cost_center' => 'PDU-SHG-PDT-PDM',
                'budget_line_charging_1' => 'MSE',
                'gl_account' => '533401',
                'budget_line_charging_2' => 'SOE-SA-Vehicle Support',
                'product' => 'SOE-SA-VEHICLE SUPPORT',
            ],
            [
                'approver_type' => 'Approver2',
                'name' => 'Luis Locsin',
                'email' => 'ldlocsin@joy-nostalg.com',
                'unit' => 'PROPERTY DEVELOPMENT UNIT',
                'type' => 'SOCIALIZED',
                'department' => 'PD & Marketing',
                'cost_center' => 'PDU-SHG-PDT-PDM',
                'budget_line_charging_1' => 'MSE',
                'gl_account' => '533401',
                'budget_line_charging_2' => 'SOE-SA-Vehicle Support',
                'product' => 'SOE-SA-VEHICLE SUPPORT',
            ],
            [
                'approver_type' => 'Approver2',
                'name' => 'Raissa Ramirez',
                'email' => 'mjramirez.everyhome@joy-nostalg.com',
                'unit' => 'PROPERTY DEVELOPMENT UNIT',
                'type' => 'SOCIALIZED',
                'department' => 'PD & Marketing',
                'cost_center' => 'PDU-SHG-PDT-PDM',
                'budget_line_charging_1' => 'MSE',
                'gl_account' => '533401',
                'budget_line_charging_2' => 'SOE-SA-Vehicle Support',
                'product' => 'SOE-SA-VEHICLE SUPPORT',
            ],
            [
                'approver_type' => 'Approver1',
                'name' => 'Belinda Santos',
                'email' => 'besantos.extraordinary@joy-nostalg.com',
                'unit' => 'PROPERTY DEVELOPMENT UNIT',
                'type' => 'SOCIALIZED',
                'department' => 'Sales Management',
                'cost_center' => 'PDU-SHG-PDT-SMD',
                'budget_line_charging_1' => 'MSE',
                'gl_account' => '533401',
                'budget_line_charging_2' => 'SOE-SA-Vehicle Support',
                'product' => 'SOE-SA-VEHICLE SUPPORT',
            ],
            [
                'approver_type' => 'Approver2',
                'name' => 'Ranulfo Ortiz',
                'email' => 'ruortiz@joy-nostalg.com',
                'unit' => 'PROPERTY DEVELOPMENT UNIT',
                'type' => 'SOCIALIZED',
                'department' => 'Sales Management',
                'cost_center' => 'PDU-SHG-PDT-SMD',
                'budget_line_charging_1' => 'MSE',
                'gl_account' => '533401',
                'budget_line_charging_2' => 'SOE-SA-Vehicle Support',
                'product' => 'SOE-SA-VEHICLE SUPPORT',
            ],
            [
                'approver_type' => 'Approver2',
                'name' => 'Joey Ng',
                'email' => 'joey.ng@joy-nostalg.com',
                'unit' => 'PROPERTY DEVELOPMENT UNIT',
                'type' => 'SOCIALIZED',
                'department' => 'Sales Management',
                'cost_center' => 'PDU-SHG-PDT-SMD',
                'budget_line_charging_1' => 'MSE',
                'gl_account' => '533401',
                'budget_line_charging_2' => 'SOE-SA-Vehicle Support',
                'product' => 'SOE-SA-VEHICLE SUPPORT',
            ],
            [
                'approver_type' => 'Approver2',
                'name' => 'Luis Locsin',
                'email' => 'ldlocsin@joy-nostalg.com',
                'unit' => 'PROPERTY DEVELOPMENT UNIT',
                'type' => 'SOCIALIZED',
                'department' => 'Sales Management',
                'cost_center' => 'PDU-SHG-PDT-SMD',
                'budget_line_charging_1' => 'MSE',
                'gl_account' => '533401',
                'budget_line_charging_2' => 'SOE-SA-Vehicle Support',
                'product' => 'SOE-SA-VEHICLE SUPPORT',
            ],
            [
                'approver_type' => 'Approver2',
                'name' => 'Raissa Ramirez',
                'email' => 'mjramirez.everyhome@joy-nostalg.com',
                'unit' => 'PROPERTY DEVELOPMENT UNIT',
                'type' => 'SOCIALIZED',
                'department' => 'Sales Management',
                'cost_center' => 'PDU-SHG-PDT-SMD',
                'budget_line_charging_1' => 'MSE',
                'gl_account' => '533401',
                'budget_line_charging_2' => 'SOE-SA-Vehicle Support',
                'product' => 'SOE-SA-VEHICLE SUPPORT',
            ],
            [
                'approver_type' => 'Approver1',
                'name' => 'Amor Calcabin',
                'email' => 'abcalcabin.extraordinary@joy-nostalg.com',
                'unit' => 'PROPERTY DEVELOPMENT UNIT',
                'type' => 'SOCIALIZED',
                'department' => 'Fulfillment Operations',
                'cost_center' => 'PDU-SHG-PDT-FOD',
                'budget_line_charging_1' => 'MSE',
                'gl_account' => '533401',
                'budget_line_charging_2' => 'SOE-SA-Vehicle Support',
                'product' => 'SOE-SA-VEHICLE SUPPORT',
            ],
            [
                'approver_type' => 'Approver2',
                'name' => 'Ranulfo Ortiz',
                'email' => 'ruortiz@joy-nostalg.com',
                'unit' => 'PROPERTY DEVELOPMENT UNIT',
                'type' => 'SOCIALIZED',
                'department' => 'Fulfillment Operations',
                'cost_center' => 'PDU-SHG-PDT-FOD',
                'budget_line_charging_1' => 'MSE',
                'gl_account' => '533401',
                'budget_line_charging_2' => 'SOE-SA-Vehicle Support',
                'product' => 'SOE-SA-VEHICLE SUPPORT',
            ],
            [
                'approver_type' => 'Approver2',
                'name' => 'Joey Ng',
                'email' => 'joey.ng@joy-nostalg.com',
                'unit' => 'PROPERTY DEVELOPMENT UNIT',
                'type' => 'SOCIALIZED',
                'department' => 'Fulfillment Operations',
                'cost_center' => 'PDU-SHG-PDT-FOD',
                'budget_line_charging_1' => 'MSE',
                'gl_account' => '533401',
                'budget_line_charging_2' => 'SOE-SA-Vehicle Support',
                'product' => 'SOE-SA-VEHICLE SUPPORT',
            ],
            [
                'approver_type' => 'Approver2',
                'name' => 'Luis Locsin',
                'email' => 'ldlocsin@joy-nostalg.com',
                'unit' => 'PROPERTY DEVELOPMENT UNIT',
                'type' => 'SOCIALIZED',
                'department' => 'Fulfillment Operations',
                'cost_center' => 'PDU-SHG-PDT-FOD',
                'budget_line_charging_1' => 'MSE',
                'gl_account' => '533401',
                'budget_line_charging_2' => 'SOE-SA-Vehicle Support',
                'product' => 'SOE-SA-VEHICLE SUPPORT',
            ],
            [
                'approver_type' => 'Approver2',
                'name' => 'Raissa Ramirez',
                'email' => 'mjramirez.everyhome@joy-nostalg.com',
                'unit' => 'PROPERTY DEVELOPMENT UNIT',
                'type' => 'SOCIALIZED',
                'department' => 'Fulfillment Operations',
                'cost_center' => 'PDU-SHG-PDT-FOD',
                'budget_line_charging_1' => 'MSE',
                'gl_account' => '533401',
                'budget_line_charging_2' => 'SOE-SA-Vehicle Support',
                'product' => 'SOE-SA-VEHICLE SUPPORT',
            ],
            
            [
                'approver_type' => 'Approver1',
                'name' => 'Hansel Morana',
                'email' => 'hpmorana@joy-nostalg.com',
                'unit' => 'PROPERTY DEVELOPMENT UNIT',
                'type' => 'PDU SHARED',
                'department' => 'Legal Management',
                'cost_center' => 'LIU-LMU',
                'budget_line_charging_1' => 'GPC',
                'gl_account' => '133751',
                'budget_line_charging_2' => 'GPC-Others',
                'product' => 'GPC-OTHERS-TRANSPORTATION',
            ],
            [
                'approver_type' => 'Approver1',
                'name' => 'Rina Villariza',
                'email' => 'rsvillariza@joy-nostalg.com',
                'unit' => 'PROPERTY DEVELOPMENT UNIT',
                'type' => 'PDU SHARED',
                'department' => 'Control Management',
                'cost_center' => 'PDU-CMG',
                'budget_line_charging_1' => 'GAE',
                'gl_account' => NULL,
                'budget_line_charging_2' => 'GAE-Cons & Others - Transpo - Stat & Compliance',
                'product' => 'PUBLIC TRANSPORTATION PDU-CMG',
            ],
            [
                'approver_type' => 'Approver1',
                'name' => 'PAYMENT THRU PCF OF OLG',
                'email' => NULL,
                'unit' => 'PROPERTY DEVELOPMENT UNIT',
                'type' => 'PDU SHARED',
                'department' => 'Finance Management',
                'cost_center' => 'PDU-FMG',
                'budget_line_charging_1' => 'GAE',
                'gl_account' => NULL,
                'budget_line_charging_2' => 'Transportation',
                'product' => 'PUBLIC TRANSPORTATION RMU',
            ],
            
        ];


        foreach($data as $item){
            Approver::updateOrCreate([
                'approver_type' => $item['approver_type'],
                'name' => $item['name'],
                'email' => $item['email'],
                'unit' => $item['unit'],
                'type' => $item['type'],
                'department' => $item['department'],
                'cost_center' => $item['cost_center'],
                'budget_line_charging_1' => $item['budget_line_charging_1'],
                'gl_account' => $item['gl_account'],
                'budget_line_charging_2' => $item['budget_line_charging_2'],
                'product' => $item['product'],
            ]);
        }
    }
}
